development:
  adapter: postgresql
  encoding: unicode
  database: generic_schema_hstore_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: generic_schema_hstore_test
  pool: 5
  
